// Package parse is responsible for read the json generated by crawler
// and parse values in Resource formats
package parse

import (
    "encoding/json"
    "io/ioutil"
    "strconv"
    "strings"
)

type Resource struct {
    Category string `json:"category"`
    TotalYear float64 `json:"total_year"`
}

// ParseResources receive the path of generated json by crawler
// and read it to parse value
func ParseResources(path string) ([]Resource) {
    data, _ := ioutil.ReadFile(path)

    resourcesArray := []Resource{}

    json_resources := []map[string]string{}
    json.Unmarshal(data, &json_resources)

    for index := range json_resources {
        json_resource := json_resources[index]

        category := json_resource["category"]
        total_year, _ := CleanValue(json_resource["total_year"])

        resource := Resource{category, total_year}
        resourcesArray = append(resourcesArray, resource)
    }

    return resourcesArray
}

// GroupByCategory receive the resources list and group values by category
func GroupByCategory(resources []Resource) (map[string]float64){
    resourcesByCategory := map[string]float64{}

    for index := range resources {
        resource := resources[index]

        resourceValue, _ := resourcesByCategory[resource.Category]
        resourcesByCategory[resource.Category] = resourceValue + resource.TotalYear
    }

    return resourcesByCategory
}

// CleanValue is a helper function to parse string into float format
// generally string is in format "130.123,00" and cleanValue converts value
// to float64
func CleanValue(value string) (float64, error) {
    cleanFormat := strings.Replace(value, ".", "", -1)
    floatFormat := strings.Replace(cleanFormat, ",", ".", 1)

    return strconv.ParseFloat(floatFormat, 64)
}
